### ISSUE TITLE
Basic working deployment on GKE

### ISSUE THREAD

**Issue by alimanfoo** [malariagen/jupyterhub#1]
Get a basic jupyterhub deployment up and running on GKE.

**Comment by slejdops** [comment]
Link to the jupyter notebook on Google cloud

http://35.188.218.198:8888/?token=89e13832479334262f64c2d5f1c7babc5d49ff99bdad0e70

**Comment by slejdops** [comment]
http://jupyterhub.malariagen.net
with GitHub authentication

**Comment by alimanfoo** [comment]
Awesome! Did this from my mobile...

**Comment by alimanfoo** [comment]
Btw sorry to be a pain, but can we put this at hub.malariagen.net? I think
it's going to be easier to remember and will avoid some spelling mistakes.

Also does this need to be under https? Or does it not matter when using
oauth?

**Comment by slejdops** [comment]
Changing the URL to http://hub.malariagen.net

The logging is handled by github in a secure connection but I'm going to update the configuration to use https.

**Comment by alimanfoo** [comment]
Great, thanks.

**Comment by alimanfoo** [comment]
Awesome.

**Comment by slejdops** [comment]
https://hub.malariagen.net

now with malariagen CAS authentication

**Comment by slejdops** [comment]
Yes, it's currently using sso-dev.

**Comment by alimanfoo** [comment]
Ok, thanks. For my own understanding, what's the reason for using sso-dev?
Does CAS need some tweaking to provide oauth support, and Ian wanted to try
this on dev first?

Sso-dev points at the same credentials as the main SSO service, is that
right? I.e., same usernames and passwords?

**Comment by slejdops** [comment]
We used sso-dev to test cas and oauth.

The current deployment is using a customised hub image that contains a CAS client.
Authentication is done via www.malariagen.net now.

**Comment by alimanfoo** [comment]
Cool, thanks!

**Comment by alimanfoo** [comment]
Small thing, but the jupyterhub logo at the top left of the initial screen is broken. Image src is /hub/logo but that 404s. Can we fix that?

**Comment by alimanfoo** [comment]
@slejdops you're gonna hate me, but can we change the domain name again to cloud.malariagen.net? For strategic reasons, it will be good to make it very clear this is a cloud service. Promise I won't ask to change again...

**Comment by alimanfoo** [comment]
Calling this done, raising separate issue to fix the logo #16
