### ISSUE TITLE
GCS FUSE mount

### ISSUE THREAD

**Issue by alimanfoo** [malariagen/jupyterhub#10]
Implement support for mounting a GCS bucket via FUSE. Can initially be read-only if that simplifies.

**Comment by alimanfoo** [comment]
@slejdops mentioned today some issues with getting the mounting to be automatic. Needs investigation.

**Comment by slejdops** [comment]
The auto mount has now been fixed.

**Comment by alimanfoo** [comment]
Thanks @slejdops. It would be great if you could add in to the issue comments a few details about what you did to fix this, so we have a record in case we or someone else hits a similar problem.

**Comment by slejdops** [comment]
The GCS bucket did not mount automatically on Jupyter notebooks. Replacing the deb gcsfuse package with one available via conda fixed it.

**Comment by alimanfoo** [comment]
jhub bucket currently mounted. needs to be buckets inside malariagen-jupyterhub. everyone can read-write (jovian).
