### ISSUE TITLE
Get helm charts working from GitHub

### ISSUE THREAD

**Issue by alimanfoo** [malariagen/jupyterhub#12]
Create a new GitHub repo for managing helm charts.

Suggest creating malariagen/jupyterhub-helm-chart repo, copying the pangeo/helm-chart setup (using travis and chartpress to build the charts, and using github pages to host the chart repository).

**Comment by slejdops** [comment]
You need to include the version number of the helm chart you are installing
`helm --debug install malariagen/malariagen  --version=v0.0.0-1  --name=jupyter -f secret-config.yaml`

**Comment by alimanfoo** [comment]
Discussed today, @slejdops has the helm charts working from his own repo, via a manual build process. Next step to migrate the helm charts into a malariagen repo, and get the CI set up to build and deploy the charts.

**Comment by slejdops** [comment]
Malariagen helm charts are here https://malariagen.github.io/helm-charts/

and built by travis

**Comment by alimanfoo** [comment]
Awesome!
