### ISSUE TITLE
Get Docker file into GitHub

### ISSUE THREAD

**Issue by alimanfoo** [malariagen/jupyterhub#13]
Put Docker file into malariagen/jupyterhub/docker/notebook/Dockerfile

**Comment by alimanfoo** [comment]
[Here](https://github.com/malariagen/agam-report-base/blob/master/install/install-conda.sh) is the way we usually install conda. This uses a [list of packages](https://github.com/malariagen/agam-report-base/blob/master/install/conda.txt) to install via conda and [another list](https://github.com/malariagen/agam-report-base/blob/master/install/pypi.txt) to install via pip.

Also would be good to install the minimum Ubuntu packages necessary to enable downloading a notebook as a PDF.

**Comment by alimanfoo** [comment]
Btw I think downloading a notebook as PDF requires xetex. I think you can get this via the texlive-xetex package, although this may incur substantial size on the image, let me know if it looks too big and maybe we can drop this.

**Comment by slejdops** [comment]
Both notebook and hub docker files are now in github
malariagen/jupyterhub/dockerfiles

The images have been pushed to dockerhub 
https://hub.docker.com/u/malariagen/

**Comment by alimanfoo** [comment]
Thanks @slejdops, that's great. 

I suggest that any further changes to these docker files we make via a pull request, with at least one review. E.g., if you want to make a change, submit a PR and request a review from me and @idwright. Similarly if I want to propose a change, I submit a PR and ask you to review. Going via PRs is good because it helps to share the knowledge and create a nice record of changes being made.
