### ISSUE TITLE
User persistent volume

### ISSUE THREAD

**Issue by alimanfoo** [malariagen/jupyterhub#2]
Provision each user with a 10GB persistent volume.

**Comment by slejdops** [comment]
Every user gets a 10GB pv on the cluster. 10GB is the default value in the jupyterhub helm chart.

 storage:
    type: dynamic
    extraVolumes: []
    extraVolumeMounts: []
    static:
      pvcName:
      subPath: '{username}'
    capacity: 10Gi

**Comment by alimanfoo** [comment]
N.B., need to think about restricting so don't end up with too many unused disks getting created.
