### ISSUE TITLE
Auto-scaling for user pods

### ISSUE THREAD

**Issue by alimanfoo** [malariagen/jupyterhub#6]
Implement automatic scaling up or down of the kubernetes cluster hosting user pods to accommodate more or less users in a cost-efficient way.

**Comment by slejdops** [comment]
We need to upgrade the Google Cloud account to non-free to test kubernetes cluster autoscaling. I'm currently hitting the CPU quota ( 8 cores in the free trial account).

**Comment by alimanfoo** [comment]
It's ok by me to upgrade the account. Do you need me and/or Vikki to do
anything? I thought we already had a paid account that Ben was using?

**Comment by slejdops** [comment]
Autoscaling has been tested. The cluster scales up and down with no issues.

**Comment by alimanfoo** [comment]
Great news! I'm on leave today so will miss our regular catch-up, and
travelling rest of the week, but look forward to catching up next week and
putting this new feature to the test.

What would be great is if we can get helm charts under a MalariaGEN GitHub
repo, then when you solve an issue like this you can link through to the
changes in the helm charts, which would be a cool way to record and share
knowledge. Ideally if you can make future changes via pull requests, with
each PR referencing the issue being resolved, that creates a very nice
record. Cc @idwright.

**Comment by alimanfoo** [comment]
@slejdops do you suspect we will see issues with slow scale-down as in pangeo? Is this something we should test?

**Comment by slejdops** [comment]
yes, it seems the cluster scales down slower that it scales up. I have experimented a little with some prePuller.hook options.

I need to do more tests.

**Comment by alimanfoo** [comment]
Call this done, will raise another issue if we get some clue on how to speed up scale down.
