### ISSUE TITLE
Dask clusters

### ISSUE THREAD

**Issue by alimanfoo** [malariagen/jupyterhub#9]
Implement support for user to create a Dask cluster with pre-emptible VMs.

**Comment by slejdops** [comment]
test cluster with a shared dask deployed to 
35.196.152.73

`from dask.distributed import Client
client = Client("35.237.190.34:8786")
client`

**Comment by slejdops** [comment]
malariagen docker image with dask deployed to cloud.malariagen.net

**Comment by alimanfoo** [comment]
Closing this one as we have working private clusters. Will raise separate issues for follow-on work.
